### ISSUE TITLE
Error: No provider for "framework:angular-filesort"!

### ISSUE THREAD

**Issue by akashthapa** [wilsonjackson/karma-angular-filesort#10]
I followed the instructions from readme. I did install module and ran test code 

**Example of karma.conf.js**
```
..
frameworks : ['jasmine', 'angular-filesort'],
...
```

**Output:**

> /Applications/XAMPP/xamppfiles/htdocs/drivio/client-boilerplate/node_modules/di/lib/injector.js:9
>       throw error('No provider for "' + name + '"!');
>       ^
> 
> Error: No provider for "framework:angular-filesort"! (Resolving: framework:angular-filesort)
>     at error (/Applications/XAMPP/xamppfiles/htdocs/drivio/client-boilerplate/node_modules/di/lib/injector.js:22:12)
>     at Object.get (/Applications/XAMPP/xamppfiles/htdocs/drivio/client-boilerplate/node_modules/di/lib/injector.js:9:13)
>     at Injector.get (/Applications/XAMPP/xamppfiles/htdocs/drivio/client-boilerplate/node_modules/di/lib/injector.js:54:19)
>     at /Applications/XAMPP/xamppfiles/htdocs/drivio/client-boilerplate/node_modules/karma/lib/server.js:143:20
>     at Array.forEach (native)
>     at Server._start (/Applications/XAMPP/xamppfiles/htdocs/drivio/client-boilerplate/node_modules/karma/lib/server.js:142:21)
>     at Injector.invoke (/Applications/XAMPP/xamppfiles/htdocs/drivio/client-boilerplate/node_modules/di/lib/injector.js:75:15)
>     at Server.start (/Applications/XAMPP/xamppfiles/htdocs/drivio/client-boilerplate/node_modules/karma/lib/server.js:103:18)
>     at Object.exports.run (/Applications/XAMPP/xamppfiles/htdocs/drivio/client-boilerplate/node_modules/karma/lib/cli.js:280:26)
>     at Object.<anonymous> (/Applications/XAMPP/xamppfiles/htdocs/drivio/client-boilerplate/node_modules/karma/bin/karma:3:23)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.runMain (module.js:604:10)
> npm ERR! Test failed.  See above for more details.

**Comment by akashthapa** [comment]
So my issue was because of lack of information provided by author on readme.

```
// karma.conf.js
module.exports = function(config) {
  config.set({
    frameworks: ['jasmine', 'angular-filesort'],
    
    files: [
      'bower_components/angular/angular.js',
      'bower_components/angular-mocks/angular-mocks.js',
      'app/**/*.js',
      'test/**/*.js'
    ],

    angularFilesort: {
      whitelist: [
        'app/**/*.js'
      ]
    }
  });
};
```

If you follow only the instruction provided as above then your test will end with error. 

**Fix is : Add following line** 

```
plugins: [
           ....
            'karma-angular-filesort'
        ],
```
