### ISSUE TITLE
TypeError: Cannot call method 'filter' of undefined

### ISSUE THREAD

**Issue by mpiasta-ca** [wilsonjackson/karma-angular-filesort#6]
Uh, not sure what's going on. Just installed your plugin for the first time. Are you missing a dependency in the package.json file?

```
C:\dev\generic-angular-app\node_modules\karma-angular-filesort\lib\sort.js:21
    files = files.filter(function (file, index) {
                  ^
TypeError: Cannot call method 'filter' of undefined
    at module.exports (C:\dev\generic-angular-app\node_modules\karma-angular-filesort\lib\sort.js:21:16)
    at emitter.emit (C:\dev\generic-angular-app\node_modules\karma-angular-filesort\lib\index.js:21:21)
    at refresh (C:\dev\generic-angular-app\node_modules\karma\lib\file_list.js:178:15)
    at start (C:\dev\generic-angular-app\node_modules\karma\lib\server.js:69:12)
    at invoke (C:\dev\generic-angular-app\node_modules\karma\node_modules\di\lib\injector.js:75:15)
    at Object.exports.start (C:\dev\generic-angular-app\node_modules\karma\lib\server.js:307:12)
    at Object.<anonymous> (C:\Program Files (x86)\JetBrains\WebStorm 10.0.4\plugins\js-karma\js_reporter\karma-intellij\lib\intellijServer.js:10:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by ihorml** [comment]
@mpiasta-ca How did you resolve this issue? I have the same issue...

**Comment by ihorml** [comment]
Just update karma to 0.13.5

**Comment by nikravi** [comment]
I have the same issue. How to fix it?

**Comment by ihorml** [comment]
@nikravi update karma  to latest version. It was my solution.

**Comment by nikravi** [comment]
@ihorml I updated to 0.13.19 and still the same. Interesting that the version 0.1.0 works fine with karma 0.13.19
